@echo off
setlocal
rem Portable launcher: works from any clone location, no absolute paths.
rem Double-click this (or the "Interview Analyzer" shortcut generated by
rem scripts\create_shortcut.ps1) to start the app.
cd /d "%~dp0"

if exist ".venv\Scripts\pythonw.exe" (
    set "PYTHONW=.venv\Scripts\pythonw.exe"
) else (
    where pythonw >nul 2>nul
    if errorlevel 1 (
        echo pythonw.exe not found. Install Python 3.10+ and/or create a
        echo .venv virtual environment first -- see README.md's Setup section.
        pause
        exit /b 1
    )
    set "PYTHONW=pythonw"
)

rem pythonw has no console, so errors are invisible by default -- capture
rem them to a log file instead of silently vanishing if something goes wrong.
rem "start /B" launches it detached and in the background, so this window
rem closes immediately instead of staying open for the whole app session.
if not exist "logs" mkdir "logs"
start "" /B "%PYTHONW%" -m interview_analyzer.app > "logs\app_launch.log" 2>&1
